spring:
  application:
    name: hospital-booking-backend
  profiles:
    default: dev

server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    enabled: false
